[tool.poetry]
name = "xiaomi_flashable_firmware_creator_gui"
version = "1.0.0"
description = "Create flashable firmware zip from MIUI Recovery ROMs!"
authors = ["yshalsager <ysh-alsager@hotmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.6"
PyQt5 = "^5.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
